name: pageview_form
version: 1.0.0
description: A Flutter package for creating a page view form with progress bar.
homepage: https://github.com/your-repo/page_view_form
documentation: https://github.com/your-repo/page_view_form#readme
license: MIT
email: julienmercier149@gmail.com
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Ajoutez ici les autres dépendances requises par votre package
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
