name: pageview_form
version: 0.1.1
description: A Flutter package for creating a page view form with progress bar.
homepage: https://github.com/juju149/pageview_form/tree/main
documentation: https://github.com/juju149/pageview_form/tree/main
license: MIT
email: julienmercier149@gmail.com
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Ajoutez ici les autres dépendances requises par votre package
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
